### ISSUE TITLE
recognize pth file 

### ISSUE THREAD

**Issue by daben233-bit** [rahzaazhar/PAN-PSEnet#8]
Hi, thank you for your excellent job. I found a few pth files in your recognition folder on gdrive and downloaded them all. But I don't know which one is the model to recognize which language. I choosed the 'hin_best.pth' to recognize the image in your demo folder, but it seems work not quite well and I can not read Hindi. So, please tell me  the meaning of abbreviation in your file name, thanks again!!

**Comment by rahzaazhar** [comment]
Hi @daben233-bit 
The .pth files under the recognition folder are the recognition model weights for each language. The letters before the underscore is the abbreviation for the language ex hin_best.pth are the weights for hindi, ban_best.pth are weights for bangla. Please clone the branch:latest of the repository and run the demo. Also did you download the detection model too?

**Comment by daben233-bit** [comment]
thank you very much😁

azhar shaikh <notifications@github.com> 于2020年9月5日周六 下午7:55写道：
